### ISSUE TITLE
Flatpak Build Support

### ISSUE THREAD

**Issue by another-sapiens** [civctp2/civctp2#433]
Hello! 

I was facing some issues running the latest release on Fedora, since running ctp2 outputs:

`error while loading shared libraries: libavutil.so.57: cannot open shared object file: No such file or directory`

Upon further investigation, it seems Fedora ships `libavutil.so.59`, and to work around this we would have to symlink the 59 to 57 inside `/usr/lib64/` so it thinks it's got the right libraries. However, this can't be done cleanly on immutable distros like Silverblue, and seems finicky - and this error was probably not intended.

I've tried Debian inside distrobox, but I wasn't able to build the project - even after installing the dependencies, library errors show up. A solution might be to use regular Docker, but I think there's a better alternative...

### Flatpak

I was thinking Flatpak would be the perfect use case for this. All the required libraries are covered by org.freedesktop.Platform and org.freedesktop.SDK respectively. Getting the manifest right _should_ mean it will always build correctly, no matter what Linux distribution it's built on, since it's self-contained. 

#### What I did

1. Clone the repository and unzip
2. Paste the GoG game data on it, without replacing the downloaded repo files
3. Create a `net.apolyton.civctp2.yaml` file on the top directory, to serve as the flatpak manifest:

```
app-id: net.apolyton.civctp2
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
command: ctp2
finish-args:
  - --share=ipc
  - --socket=wayland
  - --socket=fallback-x11
  - --socket=pulseaudio
  - --share=network

modules:
  - name: byacc
    buildsystem: autotools
    config-opts:
      - --prefix=/app
    sources:
      - type: git
        url: https://github.com/grandseiken/byacc.git
    build-commands:
      - ./configure --prefix=/app
      - make
      - make install
      - mv /app/bin/yacc /app/bin/byacc
    build-options:
        env:
            PATH: /app/bin:/usr/bin:/bin
  - name: flex
    buildsystem: autotools
    sources:
      - type: archive
        url: https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz
        sha256: e87aae032bf07c26f85ac0ed3250998c37621d95f8bd748b31f15b33c45ee995
    build-commands:
      - ./configure --prefix=/app
      - make
      - make install
  - name: civctp2
    buildsystem: autotools
    sources:
      - type: dir
        path: ./
    build-options:
      cflags: "-O3 -fuse-ld=gold"
      cxxflags: "-fpermissive -O3 -fuse-ld=gold"
    config-opts:
      - --enable-silent-rules

```

4. Run `flatpak run org.flatpak.Builder --install --user --force-clean "build/" "net.apolyton.civctp2.yaml"`

...Remember if you want to follow this on your Linux machine, you should run `flatpak install org.flatpak.Builder org.freedesktop.Sdk/x86_64/24.08 org.freedesktop.Platform/x86_64/23.08` to satisfy the dependencies.

5. `flatpak run com.civctp2.CivCTP2
`
#### Obstacle

Everything compiles, but upon running I get this:

`Messagebox(appstr.txt Error): Unable to open appstr.txt. Terminating app.`

Reading https://github.com/ptitSeb/ctp2/issues/4#issuecomment-485557012 someone suggested the data wasn't copied in the right place, but as per what I did above I'm not sure that's the issue. 

-----

Of course, this flatpak thing was all my doing. It is not necessary you help me with this if you don't wish to; but I share it in case someone finds it useful and wants to provide some assistance, since (I believe) building would be permanently simplified. :)
